/// カタカナで入力した外来語から、対応する英単語の綴りを候補に追加する。
///
/// 機械的なローマ字化ではなく、一般的な英語表記だけを明示的に登録する。
enum KatakanaEnglishCandidates {
    private static let words: [String: String] = [
        // 日常で使う物・場所
        "ベッド": "bed",
        "ボトル": "bottle",
        "カメラ": "camera",
        "カード": "card",
        "コーヒー": "coffee",
        "ドア": "door",
        "ドレス": "dress",
        "エレベーター": "elevator",
        "フード": "food",
        "ホテル": "hotel",
        "アイスクリーム": "ice cream",
        "ジャケット": "jacket",
        "キッチン": "kitchen",
        "ランチ": "lunch",
        "マップ": "map",
        "メニュー": "menu",
        "ミラー": "mirror",
        "オフィス": "office",
        "パスポート": "passport",
        "ペン": "pen",
        "ピザ": "pizza",
        "レストラン": "restaurant",
        "シャツ": "shirt",
        "ショップ": "shop",
        "ソファ": "sofa",
        "スーツ": "suit",
        "タクシー": "taxi",
        "チケット": "ticket",
        "トイレ": "toilet",
        "トレイン": "train",
        "バス": "bus",
        "ウォーター": "water",
        "ウィンドウ": "window",

        // デジタル作業
        "アクセス": "access",
        "アカウント": "account",
        "アプリ": "app",
        "アップデート": "update",
        "アップロード": "upload",
        "ブラウザ": "browser",
        "クリック": "click",
        "コード": "code",
        "コンテンツ": "content",
        "データ": "data",
        "デバッグ": "debug",
        "デバイス": "device",
        "ディスプレイ": "display",
        "ドキュメント": "document",
        "ダウンロード": "download",
        "エラー": "error",
        "ファイル": "file",
        "フォルダ": "folder",
        "インストール": "install",
        "インターフェース": "interface",
        "インターネット": "internet",
        "キーボード": "keyboard",
        "リンク": "link",
        "ログイン": "login",
        "マウス": "mouse",
        "ネットワーク": "network",
        "オプション": "option",
        "パスワード": "password",
        "プライバシー": "privacy",
        "プログラム": "program",
        "プロジェクト": "project",
        "リリース": "release",
        "セキュリティ": "security",
        "サーバー": "server",
        "サービス": "service",
        "ソフトウェア": "software",
        "スマートフォン": "smartphone",
        "システム": "system",
        "タブ": "tab",
        "テキスト": "text",
        "ユーザー": "user",
        "バージョン": "version",
        "ウェブ": "web",
        "ウェブサイト": "website",

        // 仕事・コミュニケーション
        "アジェンダ": "agenda",
        "アポイントメント": "appointment",
        "ミーティング": "meeting",
        "メッセージ": "message",
        "メール": "email",
        "プレゼンテーション": "presentation",
        "レポート": "report",
        "スケジュール": "schedule",
        "タスク": "task",
        "チーム": "team",

        // よく使う一般語
        "アイデア": "idea",
        "アイコン": "icon",
        "イメージ": "image",
        "イベント": "event",
        "ゲーム": "game",
        "グループ": "group",
        "キーワード": "keyword",
        "ラベル": "label",
        "レイアウト": "layout",
        "リスト": "list",
        "モデル": "model",
        "ニュース": "news",
        "ページ": "page",
        "パターン": "pattern",
        "プラン": "plan",
        "ポイント": "point",
        "ポリシー": "policy",
        "レスポンス": "response",
        "ルール": "rule",
        "サンプル": "sample",
        "サイズ": "size",
        "スタイル": "style",
        "タイトル": "title",
        "トピック": "topic",
        "タイプ": "type",
        "ワーク": "work"
    ]

    static func variants(for reading: String) -> [String] {
        guard let word = Self.words[reading] else {
            return []
        }
        let title = word.prefix(1).uppercased() + word.dropFirst()
        return title == word ? [word] : [word, title]
    }
}
